# This is a basic workflow to help you get started with Actions

name: Automated build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          # Semantic version range syntax or exact version of a dotnet version
          dotnet-version: '6.0'
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore ChummerGenSR4.sln
        
      - name: Find .NET
        run: ls 'C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0'
        
        
      - name: Build the solution
        run: msbuild ChummerGenSR4.sln /p:Configuration=Release -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0"
        
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: "ChummerGenSR4.zip"
          directory: "."
          path: "bin"
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: "ChummerGenSR4.zip"
          path: "ChummerGenSR4.zip"
